const companies = [
  {
    key: 1,
    name: "Leaves",
    score: 90,
    img: "hhttps://images.happycow.net/venues/1024/96/95/hcmp96956_307601.jpeg",
    product: "Coffee Shop",
    price: "",
  },
  {
    key: 2,
    name: "Milton B",
    score: 83,
    img: "https://picsum.photos/75",
    product: "Coffee Shop",
    price: "",
  },
  {
    key: 3,
    name: "Java U",
    score: 74,
    img: "https://picsum.photos/75",
    product: "Coffee Shop",
    price: "",
  },
  {
    key: 7,
    name: "VdeV",
    score: 65,
    img: "https://media.istockphoto.com/photos/mens-grey-blank-tshirt-templatefrom-two-sides-natural-shape-on-for-picture-id1134011734?k=20&m=1134011734&s=612x612&w=0&h=9kTFthlqNT6v0DIjIi-eJSwDZfSj65_qeFso7w2vFOA=",
    product: "Ceramic Plate",
    price: "$14.99",
  },
  {
    key: 8,
    name: "Buk & Nola",
    score: 92,
    img: "https://picsum.photos/75",
    product: "Kitchen Plates",
    price: "$13.99",
  },
  {
    key: 9,
    name: "Boutique Marie Dumas",
    score: 88,
    img: "https://picsum.photos/75",
    product: "Plates Bundle",
    price: "$20.50",
  },
  {
    key: 4,
    name: "Le Magasin de Chainon",
    score: 90,
    img: "https://picsum.photos/75",
    product: "Used Graphic Tee",
    price: "$2.99",
  },
  {
    key: 5,
    name: "The Good Tee",
    score: 73,
    img: "https://picsum.photos/75",
    product: "Ringspun Tee",
    price: "$6.99",
  },
  {
    key: 6,
    name: "TenTree",
    score: 62,
    img: "https://picsum.photos/75",
    product: "Cotton T-Shirt",
    price: "$7.99",
  },
];

export default companies;
